services:
  phase2_umdloop:
    container_name: phase_II_ws

    build:
      context: .
      dockerfile: Dockerfile

    stdin_open: true
    tty: true

    environment:
      - DISPLAY=${DISPLAY}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:ro
    ipc: host